"""add_link_favorite.

Revision ID: c73e9ec5e9b7
Revises: 324b639f0d37
Create Date: 2026-07-12 18:05:31.703617+00:00

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "c73e9ec5e9b7"
down_revision: str | Sequence[str] | None = "324b639f0d37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("favorite", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column("links", "favorite", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "favorite")
    # ### end Alembic commands ###
