"""add_login_token_email_index.

Revision ID: 30013aa595f0
Revises: b4c23d64330b
Create Date: 2026-09-17 09:58:36.364389+00:00

"""

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "30013aa595f0"
down_revision: str | Sequence[str] | None = "b4c23d64330b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_login_tokens_email"), "login_tokens", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_tokens_email"), table_name="login_tokens")
    # ### end Alembic commands ###
