"""add_link_status_and_expiration.

Revision ID: 008fdeef2f94
Revises: 287ecee0d6d5
Create Date: 2026-05-21 20:20:23.293564+00:00

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "008fdeef2f94"
down_revision: str | Sequence[str] | None = "287ecee0d6d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    link_status = sa.Enum("ACTIVE", "DISABLED", name="link_status")
    link_status.create(op.get_bind(), checkfirst=True)
    op.add_column("links", sa.Column("status", link_status, nullable=False, server_default="ACTIVE"))
    op.add_column("links", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "expires_at")
    op.drop_column("links", "status")
    sa.Enum(name="link_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
