"""add_user_agent_header.

Revision ID: 324b639f0d37
Revises: 7d142b1fc731
Create Date: 2026-06-27 14:29:38.769615+00:00

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "324b639f0d37"
down_revision: str | Sequence[str] | None = "7d142b1fc731"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    click_source = sa.Enum("LNKR_APP", "PUBLIC_API", name="click_source")
    click_source.create(op.get_bind(), checkfirst=True)
    # ClickSource is not backfilled because of database change.
    op.add_column("clicks", sa.Column("source", click_source, nullable=False))
    op.add_column("clicks", sa.Column("browser", sa.String(length=128), nullable=True))
    op.add_column("clicks", sa.Column("operating_system", sa.String(length=128), nullable=True))
    op.add_column("login_tokens", sa.Column("ip_address", sa.String(length=45), nullable=True))
    op.add_column("login_tokens", sa.Column("country_code", sa.String(length=2), nullable=True))
    op.add_column("login_tokens", sa.Column("browser", sa.String(length=128), nullable=True))
    op.add_column("login_tokens", sa.Column("operating_system", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login_tokens", "operating_system")
    op.drop_column("login_tokens", "browser")
    op.drop_column("login_tokens", "country_code")
    op.drop_column("login_tokens", "ip_address")
    op.drop_column("clicks", "operating_system")
    op.drop_column("clicks", "browser")
    op.drop_column("clicks", "source")
    sa.Enum(name="click_source").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
