"""add_click_country_code.

Revision ID: 7d142b1fc731
Revises: 36fe93a6ad47
Create Date: 2026-05-28 19:13:21.634941+00:00

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "7d142b1fc731"
down_revision: str | Sequence[str] | None = "36fe93a6ad47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clicks", sa.Column("country_code", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clicks", "country_code")
    # ### end Alembic commands ###
