"""add_link_password_hash.

Revision ID: 36fe93a6ad47
Revises: 008fdeef2f94
Create Date: 2026-05-25 19:32:13.359430+00:00

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "36fe93a6ad47"
down_revision: str | Sequence[str] | None = "008fdeef2f94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("links", sa.Column("password_hash", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "password_hash")
    # ### end Alembic commands ###
